# 头部菜单，title: link
menu:
  关于我: /关于我
  微博: https://weibo.com/u/5095838904
  Github: https://github.com/YiYunC
  Twitter: https://twitter.com/Michael_CHENYY
  Instagram: https://instagram.com/mr.chenyiyun

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - http://fs.open.kugou.com/3ccbd5b3c50be0fbfd6e24aa0e2c5fdb/5ca4368f/G011/M01/13/00/q4YBAFT6DhCAaLRzADIFZXM-in8160.mp3
 

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover:  /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
# gitalk:
    # 是否自动展开评论框
#    autoExpand: false
    # 应用编号
#    clientID: ''
    # 应用秘钥
#    clientSecret: ''
    # issue仓库名
#    repo: ''
    # Github名
#    owner: ''
    # Github名
#    admin: ['']
    # Ensure uniqueness and length less than 50
#    id: location.pathname
    # Facebook-like distraction free mode
#    distractionFreeMode: false

# 网站关键字
keywords: photo

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
